version: '3'
services:
  web:
    container_name: octobercms
    build: ./build
    expose:
      - "80"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: unless-stopped
    networks:
      - web
      - internal
    depends_on:
      - mysql
    volumes:
      - ./data/plugins:/var/www/html/plugins
      - ./data/themes:/var/www/html/themes
      - ${SSH_PRIVATE_KEY}:/root/.ssh/id_rsa
    environment:
      - OCTOBER_APP_URL=https://${DOMAIN}
      - OCTOBER_CMS_LINK_POLICY=secure
      - OCTOBER_PLUGINS=RainLab.Blog;RainLab.Pages;RainLab.User;ToughDeveloper.ImageResizer
      - OCTOBER_CMS_ACTIVE_THEME=${ACTIVE_THEME}
      - OCTOBER_DB_DRIVER=mysql
      - OCTOBER_DB_HOST=mysql
      - OCTOBER_DB_PORT=3306
      - OCTOBER_DB_USER=root
      - OCTOBER_DB_PASSWORD=october
      - OCTOBER_DB_NAME=october_cms
      - OCTOBER_APP_DEBUG=true
      - GIT_HOSTS=${GIT_HOSTS}
      - GIT_THEMES=${GIT_THEMES}
      - GIT_PLUGINS_FOLDER=${GIT_PLUGINS_FOLDER}
    labels:
      - "traefik.backend=october"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOMAIN}"
      - "traefik.port=80"
      - "traefik.frontend.auth.forward.address=http://forward-auth:4181"

  mysql:
    container_name: octobercms_mysql
    image: "mariadb"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=october
    networks:
      - internal

networks:
  internal:    
  web:
    external: true
