version: '3'
services:
  web:
    container_name: octobercms
    build: ./build
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - mysql
    volumes:
      - ./data/plugins:/var/www/html/plugins
      - ./data/themes:/var/www/html/themes
      - ${SSH_PRIVATE_KEY}:/root/.ssh/id_rsa
    environment:
      - OCTOBER_PLUGINS=RainLab.Blog;RainLab.Pages;RainLab.User;ToughDeveloper.ImageResizer
      - OCTOBER_CMS_ACTIVE_THEME=${ACTIVE_THEME}
      - OCTOBER_DB_DRIVER=mysql
      - OCTOBER_DB_HOST=mysql
      - OCTOBER_DB_PORT=3306
      - OCTOBER_DB_USER=root
      - OCTOBER_DB_PASSWORD=october
      - OCTOBER_DB_NAME=october_cms
      - OCTOBER_APP_DEBUG=true
      - GIT_HOSTS=${GIT_HOSTS}
      - GIT_THEMES=${GIT_THEMES}
      - GIT_PLUGINS_FOLDER=${GIT_PLUGINS_FOLDER}

  mysql:
    container_name: octobercms_mysql
    image: "mariadb"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=october
    networks:
      - internal

networks:
  internal:
